# Generated by Django 3.2.7 on 2021-10-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0002_auto_20211031_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like_gender',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
