# Generated by Django 3.2.7 on 2021-11-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0003_auto_20211031_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.FloatField(blank=True, default=11),
            preserve_default=False,
        ),
    ]
