# Generated by Django 3.2.7 on 2021-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0004_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
