# Generated by Django 3.2.7 on 2021-11-05 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ManyToManyField(blank=True, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
    ]
