# Generated by Django 3.2.7 on 2021-11-05 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0008_auto_20211105_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unliked',
            field=models.ManyToManyField(blank=True, related_name='nope', to=settings.AUTH_USER_MODEL),
        ),
    ]
