# Generated by Django 3.2.7 on 2021-11-05 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0009_profile_unliked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='r', to='pinner.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='pinner.profile')),
            ],
        ),
    ]
