# Generated by Django 3.2.7 on 2021-11-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0010_sendmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.IntegerField(),
        ),
    ]
