# Generated by Django 3.2.7 on 2021-11-08 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0011_alter_profile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unliked',
            field=models.ManyToManyField(blank=True, related_name='n', to=settings.AUTH_USER_MODEL),
        ),
    ]
