# Generated by Django 3.2.7 on 2021-11-08 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinner', '0013_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
